### ISSUE TITLE
npm run deploy error

### ISSUE THREAD

**Issue by ejabu** [cristijora/vue-tabs#63]
"The pattern in the "src" property didn't match any files."

this is full log

0 info it worked if it ends with ok
1 verbose cli [ '/home/haliib/nuxt/nodejs/bin/node',
1 verbose cli   '/home/haliib/nuxt/nodejs/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle vue-nav-tabs@0.5.7~predeploy: vue-nav-tabs@0.5.7
6 info lifecycle vue-nav-tabs@0.5.7~deploy: vue-nav-tabs@0.5.7
7 verbose lifecycle vue-nav-tabs@0.5.7~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle vue-nav-tabs@0.5.7~deploy: PATH: /home/haliib/nuxt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/haliib/explore/react/vue-tabs/node_modules/.bin:/home/haliib/flutter/flutter/bin:/home/haliib/flutter/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/go/bin:/home/haliib/nuxt/nodejs/bin:/home/haliib/nodejs/node-v10.16.0-linux-x64/bin/
9 verbose lifecycle vue-nav-tabs@0.5.7~deploy: CWD: /home/haliib/explore/react/vue-tabs
10 silly lifecycle vue-nav-tabs@0.5.7~deploy: Args: [ '-c', 'npm run build:example && gh-pages -d example/dist' ]
11 silly lifecycle vue-nav-tabs@0.5.7~deploy: Returned: code: 1  signal: null
12 info lifecycle vue-nav-tabs@0.5.7~deploy: Failed to exec deploy script
13 verbose stack Error: vue-nav-tabs@0.5.7 deploy: `npm run build:example && gh-pages -d example/dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/haliib/nuxt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/haliib/nuxt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vue-nav-tabs@0.5.7
15 verbose cwd /home/haliib/explore/react/vue-tabs
16 verbose Linux 4.15.0-50-generic
17 verbose argv "/home/haliib/nuxt/nodejs/bin/node" "/home/haliib/nuxt/nodejs/bin/npm" "run" "deploy"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error vue-nav-tabs@0.5.7 deploy: `npm run build:example && gh-pages -d example/dist`
22 error Exit status 1
23 error Failed at the vue-nav-tabs@0.5.7 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by thaycacac** [comment]
I got have the same
